name: Battle Arena

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Gerar SVG (Battle)
        run: |
          mkdir -p assets
          if [ -f package-lock.json ]; then npm ci --silent; else npm i --silent; fi
          npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BATTLE_LOGIN: thunderkat12   # força seu us_
