name: Snake

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 9 * * *"   # diário 09:00 UTC

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Gera os arquivos da cobra na própria pasta assets/
      - name: Generate snake SVGs
        uses: Platane/snk@v3
        with:
          github_user_name: thunderkat12
          outputs: |
            assets/snake.svg
            assets/snake-dark.svg?palette=github-dark

      # Faz commit no MESMO branch (main)
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update snake svg" || echo "nada para commitar"
          git push
